// 模拟分类数据
export const mockCategories = [
  { id: "1", name: "AI 智能", slug: "ai-intelligence", icon: "Brain", order: 1 },
  { id: "2", name: "开发工具", slug: "developer-tools", icon: "Wrench", order: 2 },
  { id: "3", name: "效率提升", slug: "productivity", icon: "Zap", order: 3 },
  { id: "4", name: "数据分析", slug: "data-analysis", icon: "BarChart3", order: 4 },
  { id: "5", name: "内容创作", slug: "content-creation", icon: "PenTool", order: 5 },
  { id: "6", name: "安全合规", slug: "security", icon: "Shield", order: 6 },
  { id: "7", name: "通讯协作", slug: "collaboration", icon: "Users", order: 7 },
  { id: "8", name: "其他", slug: "others", icon: "Box", order: 8 },
];

// 模拟标签数据
export const mockTags = [
  { id: "1", name: "AI" },
  { id: "2", name: "自动化" },
  { id: "3", name: "开发" },
  { id: "4", name: "效率" },
  { id: "5", name: "数据分析" },
  { id: "6", name: "写作" },
  { id: "7", name: "安全" },
  { id: "8", name: "协作" },
  { id: "9", name: "Python" },
  { id: "10", name: "JavaScript" },
  { id: "11", name: "API" },
  { id: "12", name: "机器学习" },
];

// 模拟用户数据
export const mockUsers = [
  { id: "1", name: "张三", username: "zhangsan", avatar: null },
  { id: "2", name: "李四", username: "lisi", avatar: null },
  { id: "3", name: "王五", username: "wangwu", avatar: null },
  { id: "4", name: "赵六", username: "zhaoliu", avatar: null },
  { id: "5", name: "陈七", username: "chenqi", avatar: null },
  { id: "6", name: "刘八", username: "liuba", avatar: null },
  { id: "7", name: "周九", username: "zhoujiu", avatar: null },
  { id: "8", name: "吴十", username: "wushi", avatar: null },
];

// 模拟热门技能数据
export const mockSkills = [
  {
    id: "1",
    name: "Self-Improving Agent",
    slug: "self-improving-agent",
    description: "记录经验教训、错误及修正以实现持续改进。适用于命令行工具开发、自动化脚本等场景。",
    version: "1.2.0",
    category: { id: "1", name: "AI 智能", slug: "ai-intelligence" },
    author: { id: "1", name: "张三", username: "zhangsan" },
    tags: [{ id: "1", name: "AI" }, { id: "2", name: "自动化" }],
    status: "PUBLISHED",
    downloads: 37700,
    views: 89000,
    _count: { likes: 2800, favorites: 2800, comments: 156 },
    createdAt: "2026-01-15",
    updatedAt: "2026-03-20",
  },
  {
    id: "2",
    name: "React Component Generator",
    slug: "react-component-generator",
    description: "一键生成 React 组件模板，包含 TypeScript、Storybook 和测试文件，大幅提升开发效率。",
    version: "2.1.0",
    category: { id: "2", name: "开发工具", slug: "developer-tools" },
    author: { id: "2", name: "李四", username: "lisi" },
    tags: [{ id: "3", name: "开发" }, { id: "10", name: "JavaScript" }],
    status: "PUBLISHED",
    downloads: 28500,
    views: 65200,
    _count: { likes: 1920, favorites: 2100, comments: 89 },
    createdAt: "2026-02-01",
    updatedAt: "2026-03-15",
  },
  {
    id: "3",
    name: "Smart Meeting Summarizer",
    slug: "smart-meeting-summarizer",
    description: "自动转录会议录音并生成结构化摘要，提取关键决策和行动项，让会议更有价值。",
    version: "1.5.0",
    category: { id: "3", name: "效率提升", slug: "productivity" },
    author: { id: "3", name: "王五", username: "wangwu" },
    tags: [{ id: "4", name: "效率" }, { id: "1", name: "AI" }],
    status: "PUBLISHED",
    downloads: 22400,
    views: 51800,
    _count: { likes: 1650, favorites: 1890, comments: 124 },
    createdAt: "2026-01-20",
    updatedAt: "2026-03-10",
  },
  {
    id: "4",
    name: "Data Pipeline Builder",
    slug: "data-pipeline-builder",
    description: "可视化数据管道构建工具，支持多种数据源和转换操作，让数据处理变得简单直观。",
    version: "3.0.0",
    category: { id: "4", name: "数据分析", slug: "data-analysis" },
    author: { id: "4", name: "赵六", username: "zhaoliu" },
    tags: [{ id: "5", name: "数据分析" }, { id: "9", name: "Python" }],
    status: "PUBLISHED",
    downloads: 18900,
    views: 42300,
    _count: { likes: 1380, favorites: 1520, comments: 76 },
    createdAt: "2025-12-10",
    updatedAt: "2026-02-28",
  },
  {
    id: "5",
    name: "AI Writing Assistant",
    slug: "ai-writing-assistant",
    description: "智能写作助手，提供实时语法检查、风格建议和改写功能，提升文档质量。",
    version: "1.8.0",
    category: { id: "5", name: "内容创作", slug: "content-creation" },
    author: { id: "5", name: "陈七", username: "chenqi" },
    tags: [{ id: "6", name: "写作" }, { id: "1", name: "AI" }],
    status: "PUBLISHED",
    downloads: 15600,
    views: 38900,
    _count: { likes: 1120, favorites: 1340, comments: 98 },
    createdAt: "2026-02-15",
    updatedAt: "2026-03-18",
  },
  {
    id: "6",
    name: "Security Scanner Pro",
    slug: "security-scanner-pro",
    description: "全面的安全漏洞扫描工具，支持代码审计、依赖检查和配置安全分析。",
    version: "2.3.0",
    category: { id: "6", name: "安全合规", slug: "security" },
    author: { id: "6", name: "刘八", username: "liuba" },
    tags: [{ id: "7", name: "安全" }, { id: "3", name: "开发" }],
    status: "PUBLISHED",
    downloads: 12300,
    views: 28500,
    _count: { likes: 980, favorites: 1100, comments: 67 },
    createdAt: "2025-11-20",
    updatedAt: "2026-02-20",
  },
  {
    id: "7",
    name: "Team Sync Dashboard",
    slug: "team-sync-dashboard",
    description: "团队同步仪表盘，实时展示项目进度、任务分配和阻塞问题，提升团队协作效率。",
    version: "1.4.0",
    category: { id: "7", name: "通讯协作", slug: "collaboration" },
    author: { id: "7", name: "周九", username: "zhoujiu" },
    tags: [{ id: "8", name: "协作" }, { id: "4", name: "效率" }],
    status: "PUBLISHED",
    downloads: 9800,
    views: 23400,
    _count: { likes: 760, favorites: 890, comments: 45 },
    createdAt: "2026-01-05",
    updatedAt: "2026-03-05",
  },
  {
    id: "8",
    name: "API Mock Server",
    slug: "api-mock-server",
    description: "快速搭建 API Mock 服务，支持动态响应、延迟模拟和请求记录，前后端开发更高效。",
    version: "1.6.0",
    category: { id: "2", name: "开发工具", slug: "developer-tools" },
    author: { id: "8", name: "吴十", username: "wushi" },
    tags: [{ id: "11", name: "API" }, { id: "3", name: "开发" }],
    status: "PUBLISHED",
    downloads: 8500,
    views: 19800,
    _count: { likes: 620, favorites: 750, comments: 38 },
    createdAt: "2025-12-25",
    updatedAt: "2026-02-15",
  },
  {
    id: "9",
    name: "ML Model Trainer",
    slug: "ml-model-trainer",
    description: "简化机器学习模型训练流程，提供自动化超参数调优和模型评估功能。",
    version: "0.9.0",
    category: { id: "1", name: "AI 智能", slug: "ai-intelligence" },
    author: { id: "2", name: "李四", username: "lisi" },
    tags: [{ id: "12", name: "机器学习" }, { id: "9", name: "Python" }],
    status: "PUBLISHED",
    downloads: 7200,
    views: 16500,
    _count: { likes: 540, favorites: 680, comments: 52 },
    createdAt: "2026-02-25",
    updatedAt: "2026-03-22",
  },
  {
    id: "10",
    name: "Code Review Helper",
    slug: "code-review-helper",
    description: "智能代码审查助手，自动检测潜在问题、提供优化建议，提升代码质量。",
    version: "1.1.0",
    category: { id: "2", name: "开发工具", slug: "developer-tools" },
    author: { id: "1", name: "张三", username: "zhangsan" },
    tags: [{ id: "3", name: "开发" }, { id: "1", name: "AI" }],
    status: "PUBLISHED",
    downloads: 6500,
    views: 14200,
    _count: { likes: 480, favorites: 590, comments: 41 },
    createdAt: "2026-03-01",
    updatedAt: "2026-03-25",
  },
];

// 热门标签（用于首页展示）
export const hotTags = ["AI", "自动化", "开发", "效率", "Python", "JavaScript"];
